version: "3.9"

services:
  app:
    build:
      context: .
    container_name: "AutomationTestCase"
    command: >
      sh -c "python3 manage.py makemigrations --noinput && \
                 python3 manage.py migrate --noinput && \
                 python3 manage.py collectstatic --noinput && \
                 python3 manage.py createsuperuser --user superuser --email admin@localhost --noinput; \
                 python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/src

  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres-data: