# Generated by Django 4.1.5 on 2023-01-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_alter_drivermodel_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverModel',
            new_name='Driver',
        ),
    ]
