# Generated by Django 4.1.5 on 2023-01-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_rename_drivermodel_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='initial.testcase')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_senario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='initial.testsenario'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('click', 'Click'), ('move_to_element', 'Move To Element'), ('find_element', 'Find Element')], max_length=25)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial.element')),
            ],
        ),
    ]
