# Generated by Django 4.1.5 on 2023-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_element_testcase_testsenario_teststep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('click', 'Click'), ('move_to_element', 'Move To Element'), ('find_element', 'Find Element'), ('send_keys', 'Send Keys')], max_length=25),
        ),
    ]
