# Generated by Django 4.1.5 on 2023-01-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_alter_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('open_browser', 'Open Browser'), ('click', 'Click'), ('move_to_element', 'Move To Element'), ('find_element', 'Find Element'), ('send_keys', 'Send Keys'), ('close', 'Close'), ('back', 'Back'), ('refresh', 'Refresh')], max_length=25),
        ),
    ]
