# Generated by Django 4.1.5 on 2023-01-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_alter_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='element',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_senario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial.testsenario'),
        ),
    ]
