# Generated by Django 4.1.5 on 2023-01-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0007_remove_action_element_alter_testcase_test_senario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
