# Generated by Django 4.1.5 on 2023-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0010_rename_testsenario_testscenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='step',
            field=models.JSONField(default={'name': 'for test'}),
            preserve_default=False,
        ),
    ]
