# Generated by Django 4.1.5 on 2023-01-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_step',
        ),
        migrations.AddField(
            model_name='teststep',
            name='test_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_steps', to='initial.testcase'),
            preserve_default=False,
        ),
    ]
