# Generated by Django 4.1.5 on 2023-02-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
